"""add name to locations

Revision ID: 3f23bafe767c
Revises: 8018710e429d
Create Date: 2025-05-16 00:19:54.065758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f23bafe767c'
down_revision: Union[str, None] = '8018710e429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
    op.execute(
        "UPDATE locations SET name = '' WHERE name IS NULL"
    )
    # 3) Add NOT NULL constraint
    op.alter_column(
        'locations',
        'name',
        existing_type=sa.String(),
        nullable=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###
