"""update colum displayname to display_name in User table

Revision ID: 49cf34bd191c
Revises: a9bce6a52904
Create Date: 2025-05-13 11:54:43.056901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cf34bd191c'
down_revision: Union[str, None] = 'a9bce6a52904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.drop_index('ix_users_displayname', table_name='users')
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.drop_column('users', 'displayname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('displayname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.create_index('ix_users_displayname', 'users', ['displayname'], unique=False)
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
