"""Fix Plan-Location back_populates and add Penalty.user_id

Revision ID: cd3c254a33b9
Revises: 8b8d9ef60629
Create Date: 2025-05-15 18:46:13.546052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3c254a33b9'
down_revision: Union[str, None] = '8b8d9ef60629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penalties', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('penalties', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('penalties', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'penalties', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'penalties', type_='foreignkey')
    op.drop_column('penalties', 'updated_at')
    op.drop_column('penalties', 'created_at')
    op.drop_column('penalties', 'user_id')
    # ### end Alembic commands ###
