"""add penalty_id to approval requests

Revision ID: e2f3g4h5i6j7
Revises: d1e2f3g4h5i6
Create Date: 2025-08-25 12:16:15.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f3g4h5i6j7'
down_revision: Union[str, None] = 'd1e2f3g4h5i6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add penalty_id column to penalty_approvals table
    op.add_column('penalty_approvals', sa.Column('penalty_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'penalty_approvals', 'penalties', ['penalty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove penalty_id column from penalty_approvals table
    op.drop_constraint(None, 'penalty_approvals', type_='foreignkey')
    op.drop_column('penalty_approvals', 'penalty_id')
    # ### end Alembic commands ###
