"""Remove status column from penalties table

Revision ID: 54cc51f8edb8
Revises: 4df34c4b3e23
Create Date: 2025-08-28 18:39:34.077673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cc51f8edb8'
down_revision: Union[str, None] = '4df34c4b3e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penalties', 'status')
    op.alter_column('penalty_approval_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('plan_participants', 'penalty_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_participants', 'penalty_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('penalty_approval_requests', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('penalties', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
