"""add display_name column to User table

Revision ID: a9bce6a52904
Revises: a97e42637fd9
Create Date: 2025-05-13 11:21:27.290261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bce6a52904'
down_revision: Union[str, None] = 'a97e42637fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('displayname', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_displayname'), 'users', ['displayname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_displayname'), table_name='users')
    op.drop_column('users', 'displayname')
    # ### end Alembic commands ###
