"""add_penalty_status_to_plan_participants

Revision ID: b1c2d3e4f5g6
Revises: 957a989171e3
Create Date: 2025-08-20 23:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c2d3e4f5g6'
down_revision: Union[str, None] = '957a989171e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add penalty_status column to plan_participants table
    op.add_column('plan_participants', sa.Column('penalty_status', sa.String(), nullable=False, server_default='none'))
    
    # Add penalty_completed_at column to plan_participants table
    op.add_column('plan_participants', sa.Column('penalty_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove penalty_completed_at column from plan_participants table
    op.drop_column('plan_participants', 'penalty_completed_at')
    
    # Remove penalty_status column from plan_participants table
    op.drop_column('plan_participants', 'penalty_status')
    # ### end Alembic commands ###
