name = "puctee-api"
compatibility_date = "2024-01-01"
main = "app/main.py"

# Workers configuration
workers_dev = true
route = ""
zone_id = ""

# Compatibility flags for Python
compatibility_flags = ["python_workers"]

[observability]
enabled = true

# Environment variables (non-secret)
[vars]
ENVIRONMENT = "production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "30"
AWS_REGION = "ap-northeast-1"
APNS_USE_SANDBOX = "false"

# Secrets - Set these using: wrangler secret put <KEY>
# Required secrets:
# - DATABASE_URL (Supabase/Neon connection string)
# - SECRET_KEY
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_S3_BUCKET
# - REDIS_URL (Optional if using Supabase Realtime)
# - SUPABASE_URL (If using Supabase)
# - SUPABASE_ANON_KEY (If using Supabase)
# - APNS_SECRET_ARN
# - APNS_AUTH_KEY_ID
# - APNS_TEAM_ID
# - APNS_BUNDLE_ID

# Limits
[limits]
cpu_ms = 50000

# Build configuration
[build]
command = ""

# Development configuration
[env.development]
vars = { ENVIRONMENT = "development", APNS_USE_SANDBOX = "true" }

# Production configuration
[env.production]
vars = { ENVIRONMENT = "production", APNS_USE_SANDBOX = "false" }
