"""add_arrival_status_to_plan_participants

Revision ID: 957a989171e3
Revises: ee754dc46c4c
Create Date: 2025-06-01 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957a989171e3'
down_revision: Union[str, None] = 'ee754dc46c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to plan_participants table
    op.add_column('plan_participants', sa.Column('arrival_status', sa.String(), nullable=True))
    op.add_column('plan_participants', sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True))
    
    # Remove arrival_status column from plans table
    op.drop_column('plans', 'arrival_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add arrival_status column to plans table
    op.add_column('plans', sa.Column('arrival_status', sa.String(), nullable=True))
    
    # Remove new columns from plan_participants table
    op.drop_column('plan_participants', 'checked_at')
    op.drop_column('plan_participants', 'arrival_status')
    # ### end Alembic commands ###
