"""add_plan_invites_relationship

Revision ID: c1a4bb4bd041
Revises: 3493fbb49a22
Create Date: 2025-05-16 20:18:14.148414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a4bb4bd041'
down_revision: Union[str, None] = '3493fbb49a22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
