"""remove_trust_score_from_users

Revision ID: ee754dc46c4c
Revises: 92f3a2c1f4aa
Create Date: 2025-06-01 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee754dc46c4c'
down_revision: Union[str, None] = '92f3a2c1f4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trust_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trust_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###
