"""rename and update penalty approvals table

Revision ID: f3g4h5i6j7k8
Revises: e2f3g4h5i6j7
Create Date: 2025-08-25 12:24:20.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3g4h5i6j7k8'
down_revision: Union[str, None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename table from penalty_approvals to penalty_approval_requests
    op.rename_table('penalty_approvals', 'penalty_approval_requests')
    
    # Add missing columns
    op.add_column('penalty_approval_requests', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('penalty_approval_requests', sa.Column('proof_image_url', sa.String(), nullable=True))
    op.add_column('penalty_approval_requests', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('penalty_approval_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update the index name
    op.drop_index('ix_penalty_approvals_id', table_name='penalty_approval_requests')
    op.create_index(op.f('ix_penalty_approval_requests_id'), 'penalty_approval_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the changes
    op.drop_index(op.f('ix_penalty_approval_requests_id'), table_name='penalty_approval_requests')
    op.create_index('ix_penalty_approvals_id', 'penalty_approval_requests', ['id'], unique=False)
    
    # Remove added columns
    op.drop_column('penalty_approval_requests', 'updated_at')
    op.drop_column('penalty_approval_requests', 'status')
    op.drop_column('penalty_approval_requests', 'proof_image_url')
    op.drop_column('penalty_approval_requests', 'comment')
    
    # Rename table back
    op.rename_table('penalty_approval_requests', 'penalty_approvals')
    # ### end Alembic commands ###
